on: [push]
name: build
jobs:
  runhaskell:
    name: Build My Resume
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: haskell/actions/setup@v1
      - run: runghc Main.hs cn >> latex/resume-cn.tex

      - uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            latex/resume-cn.tex
          extra_fonts:
            latex/*.otf

      - name: Resume Release
        uses: softprops/action-gh-release@v1
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Release My Resume
#          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
          files: |
            latex/resume-cn.pdf